### ISSUE TITLE
update homeassistont core 2025.6.0 会出现错误如下

### ISSUE THREAD

**Issue by lambilly** [dscao/ezviz#2]
日志记录器: homeassistant.config_entries
来源: config_entries.py:749
首次出现: 15:19:32 (3 次出现)
上次记录: 15:19:45

Error setting up entry ezviz_cn-1c6f01ea for ezviz
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ezviz/__init__.py", line 76, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, component)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

**Comment by lambilly** [comment]
日志记录器: homeassistant.helpers.frame
来源: helpers/frame.py:335
首次出现: 15:19:25 (1 次出现)
上次记录: 15:19:25

Detected that custom integration 'ezviz' sets option flow config_entry explicitly, which is deprecated at custom_components/ezviz/config_flow.py, line 137: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/dscao/ezviz/issues

**Comment by dscao** [comment]
fixed https://github.com/dscao/ezviz/commit/e50dcb8c46bd3c137b900a80982a772ab546984d

**Comment by dscao** [comment]
第二个问题晚些时间修复
